title " "
logo: https://d1csarkz8obe9u.cloudfront.net/posterpreviews/travel-%26-tourism-logo-design-template-c613bcb6c381ed8ead4ce8549a79edda_screen.jpg?ts=1599762630
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://rodzapalv.github.io

nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/rodzapalv/rodzapalv.github.io
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
